name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale Issue'
        stale-pr-message: 'Stale pull request'
        stale-issue-label: 'No Activity for a while on this issue.'
        stale-pr-label: 'No Pull Request Activity'
